language: ruby
cache: bundler
sudo: required
bundler_args: --without development --jobs 2

services:
  - redis-server
  - memcached

addons:
  postgresql: "9.6"
  chrome: stable
  artifacts:
    paths:
      - ./tmp/screenshots
env:
  global:
    - DB=postgresql
    - KINDLEGEN_PATH=/tmp/kindlegen/kindlegen
    - ES_VERSION=2.3.3
    - CHROME_DRIVER_VERSION=2.36
    - RAILS_ENV=test

before_install:
  - sudo apt-get install imagemagick
  - wget "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip" -O /tmp/chromedriver.zip
  - unzip /tmp/chromedriver.zip -d /tmp/
  - mv /tmp/chromedriver /home/travis/bin/
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp
  - mkdir /tmp/kindlegen
  - wget -O - http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz | tar xz --directory=/tmp/kindlegen


before_script:
  - psql -c 'create database feedbin_test;' -U postgres
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - curl http://127.0.0.1:9200/

script:
  - bin/rails test test:system
